# Choose the name and namespace for your serviceAccount
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argocd
  namespace: argocd
secrets:
- name: argocd-sa-token
---
apiVersion: v1
kind: Secret
metadata:
  namespace: argocd
  name: argocd-sa-token
  annotations:
    kubernetes.io/service-account.name: argocd
type: kubernetes.io/service-account-token
